### ISSUE TITLE
please sign released tarballs with new GPG key

### ISSUE THREAD

**Issue by sunweaver** [openwall/scanlogd#2]
@solardiz your upstream release tarballs are still signed with a PGP-2 key. PGP-2 support has been deprecated in GnuPG 2. Please update your signing key. Thanks,

Mike (aka sunweaver at debian.org who is currently fixing scanlogd in Debian, probably too late for the bullseye release)

**Comment by solardiz** [comment]
Let's figure out what we do with #1 and whether it's an important enough change to make a new release with - if so, only the new release would need to be signed with the new key, I guess.

Thank you for fixing the Debian package! I assume this will include dropping Debian's wrong CLK_TCK patch that made scanlogd miss scans on some archs.

**Comment by solardiz** [comment]
Fixed with the 2.2.8 release.
