### ISSUE TITLE
Listen transit traffic [Question]

### ISSUE THREAD

**Issue by iglov** [openwall/scanlogd#3]
Hi there! Is it possible to somehow listen with scanlogd transit traffic? For example: Host A (1.1.1.1) -> host B (1.1.1.2 (scanlogd)) -> host C (1.1.1.3) - i want to detect NMAP from host A to host C through host B with scanlogd. At this moment, scanlogd can't detect it, may be i do something wrong? :)

**Comment by solardiz** [comment]
Hi. Sure, if you build with libpcap or libnids support. (BTW, the difference between these two is that direct libpcap is relatively lightweight but wouldn't detect scans with fragmented IP packets, whereas libnids also handles fragmented IP packets.)

**Comment by iglov** [comment]
Do i understand correctly, that i should just define `SCANLOGD_DEVICE` for ex.: `#define SCANLOGD_DEVICE "br0" in params.h` ?

**Comment by iglov** [comment]
I have compiled it with libnet and libnids (`make libnids`) and it seems now it works as expected, thank you @solardiz for scanlogd ;)
But i have another one question, maybe it is offtop. Let's return to old scheme `Host A (1.1.1.1) -> host B (1.1.1.2 (scanlogd)) -> host C (1.1.1.3)` what if i make openvpn tunnel from host A to host B, will i see nmap traffic there with scanlogd? Cuz for some reason, i can't see this traffic even with tcpdump, i dunno why :(

**Comment by solardiz** [comment]
> what if i make openvpn tunnel from host A to host B, will i see nmap traffic there with scanlogd?

Probably yes, on the `tun0` interface or such, or if monitoring all interfaces.

Also, the program or library (e.g., libnids) that is using libpcap should know to skip the link-level header (if any), and thus should know its expected size for the given interface type. I don't recall what that size is for tunnel interfaces, and don't know whether libnids knows it. I think you should just try and see what happens.

> Cuz for some reason, i can't see this traffic even with tcpdump, i dunno why :(

Maybe you're not running tcpdump against the right interface.

**Comment by iglov** [comment]
Yeah, with `libnids` and `#define SCANLOGD_DEVICE "all"`  all works as expected, i can see `nmap -sS` traffic. Thank you @solardiz 4 ur time! I am really appreciate that!
